import fs from "fs";
import Yaml from "yaml";
import { fromPairs, identity, pickBy } from "lodash";

import { Config } from "./interfaces";

export const getConfigYaml = <Stages, JobNames>(
  config: Config<Stages, JobNames>
) => {
  const { jobs, ...output } = pickBy(
    {
      stages: config.stages,
      variables: config.variables,
      jobs: fromPairs(
        config.jobs.map(({ name, ...job }) => [name, pickBy(job, identity)])
      ),
    },
    identity
  );

  const ymlContent = Yaml.stringify({
    ...output,
    ...jobs,
  });

  return `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

${ymlContent}
`;
};

export const writeConfigToFile = (
  contents: string,
  outputFile: string
): void => {
  fs.writeFile(outputFile, contents, "utf8", (error) => {
    if (error) {
      console.error(error);
      process.exit(1);
    } else {
      console.log("Success");
      process.exit(0);
    }
  });
};
